#!/usr/bin/env python3
"""
update_ips.py — refresh AI-service IP ranges from the Cloudflare Zero Trust
Resource Library and rewrite the VPN config files in this repo.

Pure stdlib (no pip installs needed in CI).

For each service it:
  1. pulls authoritative hostnames from CF resource-library/applications
  2. resolves them to IPv4 + IPv6 over DNS
  3. aggregates to /24 (v4) and /48 (v6)
  4. writes data/<service>.json
  5. rewrites every marker block tagged for that service inside *.conf
     (WireGuard) and *.ovpn (OpenVPN) files.

Marker block format (the script only edits BETWEEN the markers):
  WireGuard (.conf):
    # >>> AI-IPS:openai (auto-generated by scripts/update_ips.py — do not edit) >>>
    AllowedIPs = <v4...>, <v6...>
    # <<< AI-IPS:openai <<<
  OpenVPN (.ovpn):
    # >>> AI-IPS:openai (auto-generated by scripts/update_ips.py — do not edit) >>>
    route <ip> <mask>
    route -6 <cidr>
    # <<< AI-IPS:openai <<<

Env:
  CF_APP_RO_KEY      Cloudflare API token with resource-library read access
  CF_ACCOUNT_ID      Cloudflare account id
"""
import os, re, sys, json, ipaddress, datetime, urllib.request, urllib.parse, urllib.error
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "data"

# service -> CF resource-library exact application name to match
SERVICES = {
    "openai": "ChatGPT",
    "claude": "Claude",
}

# Static "floor" CIDRs always unioned with the freshly-resolved ranges, then
# collapsed. Use this for services that publish a stable, authoritative block
# wider than a single just-resolved /24 (so we never blackhole IPs that live in
# the block but didn't happen to resolve this run). Leave empty for services
# behind shared anycast (e.g. OpenAI on Cloudflare) where resolved /24s ARE the
# value and a wide floor would just pull in unrelated traffic.
STATIC = {
    "openai": {"ipv4": [], "ipv6": []},
    "claude": {
        # 160.79.104.0/21 = Anthropic Inc. AS399230 (api/claude.ai core).
        # Resolved GCLB front-ends (34.36.x) are picked up dynamically each run.
        # NOTE: assets.anthropic.com used to sit on AWS CloudFront (13.35.0.0/16),
        # but it no longer resolves there and a /16 CloudFront block is far too
        # broad for a split tunnel, so it is intentionally dropped.
        "ipv4": ["160.79.104.0/21"],
        # 2607:6bc0::/32 = Anthropic v6.
        "ipv6": ["2607:6bc0::/32"],
    },
}

CF_API = "https://api.cloudflare.com/client/v4"


def cf_hostnames(token, account, app_name, search):
    url = "%s/accounts/%s/resource-library/applications?%s" % (
        CF_API, account, urllib.parse.urlencode({"search": search, "limit": 25}))
    req = urllib.request.Request(url, headers={"Authorization": "Bearer " + token})
    with urllib.request.urlopen(req, timeout=30) as r:
        d = json.load(r)
    for a in (d.get("result") or []):
        if a.get("name") == app_name:
            return sorted(set(a.get("hostnames") or []))
    raise SystemExit("CF: application %r not found (search=%r)" % (app_name, search))


DOH = "https://1.1.1.1/dns-query"


def _doh(name, rrtype):
    """Resolve one name/type via Cloudflare 1.1.1.1 DoH JSON. Pure stdlib."""
    q = urllib.parse.urlencode({"name": name, "type": rrtype})
    req = urllib.request.Request(DOH + "?" + q,
                                 headers={"accept": "application/dns-json"})
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            d = json.load(r)
    except (urllib.error.URLError, TimeoutError, ValueError):
        return []
    want = 1 if rrtype == "A" else 28
    return [a["data"] for a in (d.get("Answer") or []) if a.get("type") == want]


def resolve(hostnames):
    """Resolve A + AAAA per hostname via 1.1.1.1 DoH (resolver-deterministic,
    independent of the CI runner's own DNS). Returns (v4set, v6set)."""
    v4, v6 = set(), set()
    for h in hostnames:
        for v in _doh(h, "A"):
            v4.add(v)
        for v in _doh(h, "AAAA"):
            v6.add(v)
    return v4, v6


def aggregate(v4, v6, floor4=None, floor6=None):
    n4 = sorted({ipaddress.ip_network(ip + "/24", strict=False) for ip in v4},
                key=lambda n: int(n.network_address))
    n6 = sorted({ipaddress.ip_network(ip + "/48", strict=False) for ip in v6},
                key=lambda n: int(n.network_address))
    # union resolved ranges with the static authoritative floor, then collapse
    for c in (floor4 or []):
        n4.append(ipaddress.ip_network(c))
    for c in (floor6 or []):
        n6.append(ipaddress.ip_network(c))
    n4 = [str(x) for x in ipaddress.collapse_addresses(n4)]
    n6 = [str(x) for x in ipaddress.collapse_addresses(n6)]
    return n4, n6


def render_block(service, ext, v4, v6):
    """Return the lines that go BETWEEN the markers, for the given file type."""
    if ext == ".conf":  # WireGuard
        parts = ", ".join(v4 + v6)
        return ["AllowedIPs = " + parts]
    if ext == ".ovpn":  # OpenVPN
        lines = []
        for cidr in v4:
            net = ipaddress.ip_network(cidr)
            lines.append("route %s %s" % (net.network_address, net.netmask))
        for cidr in v6:
            lines.append("route -6 %s" % cidr)
        return lines
    raise ValueError("unsupported ext " + ext)


def rewrite_file(path, service, v4, v6):
    text = path.read_text()
    start = re.compile(r"^[ \t]*#[ \t]*>>> AI-IPS:%s\b.*$" % re.escape(service), re.M)
    end = re.compile(r"^[ \t]*#[ \t]*<<< AI-IPS:%s\b.*$" % re.escape(service), re.M)
    sm = start.search(text)
    if not sm:
        return False  # no block for this service in this file
    em = end.search(text, sm.end())
    if not em:
        raise SystemExit("%s: opening marker for %s without closing marker" % (path, service))
    body = "\n".join(render_block(service, path.suffix, v4, v6))
    new = text[:sm.end()] + "\n" + body + "\n" + text[em.start():]
    if new != text:
        path.write_text(new)
        return True
    return False


def main():
    token = os.environ.get("CF_APP_RO_KEY")
    account = os.environ.get("CF_ACCOUNT_ID")
    if not token or not account:
        sys.exit("CF_APP_RO_KEY and CF_ACCOUNT_ID must be set")
    DATA.mkdir(exist_ok=True)
    conf_files = sorted(list(REPO.glob("*.conf")) + list(REPO.glob("*.ovpn")) +
                        list(REPO.glob("wg-*.conf")))
    conf_files = sorted(set(conf_files))
    changed = []
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    for service, app_name in SERVICES.items():
        hosts = cf_hostnames(token, account, app_name, service)
        v4set, v6set = resolve(hosts)
        floor = STATIC.get(service, {})
        v4, v6 = aggregate(v4set, v6set, floor.get("ipv4"), floor.get("ipv6"))
        data = {
            "service": service,
            "application": app_name,
            "source": "cloudflare-resource-library",
            "resolver": "1.1.1.1-doh",
            "updated": now,
            "hostnames": hosts,
            "ipv4": v4,
            "ipv6": v6,
            "raw": {
                "ipv4": sorted(v4set, key=lambda ip: tuple(int(o) for o in ip.split("."))),
                "ipv6": sorted(v6set),
            },
        }
        out = DATA / ("%s.json" % service)
        prev = out.read_text() if out.exists() else None
        # compare ignoring the 'updated' timestamp so we only churn on real changes
        def _norm(s):
            try:
                o = json.loads(s); o.pop("updated", None); return json.dumps(o, sort_keys=True)
            except Exception:
                return s
        new_json = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
        if prev is None or _norm(prev) != _norm(new_json):
            out.write_text(new_json)
            changed.append(str(out.relative_to(REPO)))
        for f in conf_files:
            if rewrite_file(f, service, v4, v6):
                changed.append(str(f.relative_to(REPO)))
        print("%-7s hosts=%d v4=%d v6=%d" % (service, len(hosts), len(v4), len(v6)))
    if changed:
        print("CHANGED:")
        for c in sorted(set(changed)):
            print("  " + c)
    else:
        print("no changes")


if __name__ == "__main__":
    main()
